## ITOC Config ##

title   = "Grafana UIM Adapter Configuration"

[adapter]
ipaddress = ""
port = "8089"

[uim]
ipaddress   = "" ##ip:port
username      = "" ##apiusername
password     = "" #apipassword
